name: Deployment

on:
  push:
    branches:
      - main

jobs:
  hello_world:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v2
        with: 
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with: 
          node-version: '22'
      - name: install dependencies
        run: npm install
      - name: lint
        run: npm run eslint